mysql:
  url: jdbc:mysql://172.16.65.95:3306/service_instance_db?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf-8&autoReconnect=true&useSSL=false&serverTimezone=Asia/Shanghai
  username: root
  password: 123456

eureka:
  instance: story-eureka.apps.pas.cloud.dhc.com.cn

